name: pinput
description: Pin code input (OTP) text field, iOS SMS autofill, Android SMS autofill One Time Code, Password, Passcode, Captcha, Security, Coupon, Wowcher, 2FA, Two step verification
homepage: https://github.com/Tkko/Flutter_PinPut
repository: https://github.com/Tkko/Flutter_PinPut
version: 2.2.15

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.0"


dependencies:
  flutter:
    sdk: flutter
  # smart_auth: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1